### ISSUE TITLE
Support for `.tsx`/`typescriptreact` files

### ISSUE THREAD

**Issue by redhair** [mylesmmurphy/prettify-ts#10]
Firstly, thank you for creating this wonderful extension. I'm going to get a ton of use out of this. One thing I noticed was that if I had a type in a `.tsx` file that the plugin wasn't working as expected. I added fix for this and it appeared to work on my local. I'd appreciate a second set of eyes on this however to make sure I'm not missing anything critical. Thank you again for the great extension ❤️

**Comment by mylesmmurphy** [comment]
Hi @redhair! Thank you so much for submitting this issue and a PR with it. 🚀 At first glance, your PR looks great. Going to test and will hopefully merge and release in the next couple of days. Really appreciate your work on this!

**Comment by mylesmmurphy** [comment]
Thanks again for your work on this. Just pushed v0.0.17 which includes this fix. 💯
