### ISSUE TITLE
Optional properties with question mark display redundantly

### ISSUE THREAD

**Issue by christophercook** [mylesmmurphy/prettify-ts#17]
When inspecting a type which has optional properties, the property displays with _both_ a question mark and `| undefined`

I expect only one or the other, preferably the question mark shorthand.

![Screenshot 2024-03-13 at 10 24 19 PM](https://github.com/mylesmmurphy/prettify-ts/assets/1742658/545bc2cd-fbdf-4281-93e9-47ef2837453b)

**Comment by mylesmmurphy** [comment]
Hey @christophercook! Thanks for mentioning this. I confirmed the default VSCode preview behavior is to only show the question mark, and not the union with undefined. I will get this updated ASAP!

**Comment by mylesmmurphy** [comment]
This issue has been resolved in the latest release [v0.0.18](https://github.com/mylesmmurphy/prettify-ts/releases/tag/v0.0.18) 👍
