### ISSUE TITLE
Truncate or skip expansion of `Element` related types.

### ISSUE THREAD

**Issue by FractalHQ** [mylesmmurphy/prettify-ts#19]
Currently, if an object or interface contains a `Element` (or extends it, i.e. `HTMLElement`), then the tooltip get very slow and the content explodes beyond the max length, cutting off everything after it:

<img src="https://github.com/mylesmmurphy/prettify-ts/assets/55504972/4532749a-0edb-45cd-b84f-a1c961106e34" width="400" />

Would it be possible to check for instance of `Element` and just show the type name, i.e. `HTMLButtonElement` / `HTMLInputElement`?  Happy to take a stab.

Thanks for making this btw!!  It's a great idea, and an extremely useful extension 🙏💙

**Comment by mylesmmurphy** [comment]
Hey @FractalHQ! Sorry it took me so long to get back to you. Thanks for your feedback :)

This is half-implemented currently. If you navigate to the extensions settings, you'll actually see a list of types that can be ignored and behave the way you described. For instance, you can add `HTMLElement `, `React.Component`, etc.

The issue I am facing with the current implementation is this feature only works if the types in that list are available in the global scope of the project. In other words, if you add a type to ignore like `HTMLElement`, and then navigate to a project that does not have that defined, it crashes the prettification. So far I have no found a way around it. 🤔  I am continuing to look into this, and when I do, plan on extending the list of ignored types!

**Comment by FractalHQ** [comment]
Ah ok, that's too bad there's no simple way to check for or catch those errors before crashing (I haven't looked into it but I trust you have 😅).  Let me know if there's anything you'd like me to look into or take a stab at -- looking forward to seeing improvements here either way!

Thanks again for the great extension 🙏
