### ISSUE TITLE
Prettify errors?

### ISSUE THREAD

**Issue by adriangalilea** [mylesmmurphy/prettify-ts#33]
Any chance this extension could prettify the awful type errors on hover?

**Comment by mylesmmurphy** [comment]
Hey @adriangalilea!

Currently that is out of scope for this extension because of another popular option found here:
https://github.com/yoavbls/pretty-ts-errors

Please let me know if this is what you were looking for!

**Comment by adriangalilea** [comment]
> Hey @adriangalilea!
> 
> 
> 
> Currently that is out of scope for this extension because of another popular option found here:
> 
> https://github.com/yoavbls/pretty-ts-errors
> 
> 
> 
> Please let me know if this is what you were looking for! 

Yup, that was it, many thanks.😊
