### ISSUE TITLE
[bug] wrong type suggestion

### ISSUE THREAD

**Issue by wael-boss** [mylesmmurphy/prettify-ts#35]
top suggestion is the pretify suggestion and it should be like the bottom one
![Screenshot 2024-09-05 231652](https://github.com/user-attachments/assets/d7ef4e71-73d4-4b0a-8f42-296d66e728fc)

**Comment by mylesmmurphy** [comment]
Hey @wael-boss, thanks for your feedback 😄 I believe this is a duplicate of issue #29, which I have a code change for and should be addressed in the next release! Closing as a duplicate for now.
