### ISSUE TITLE
How to see long definitions

### ISSUE THREAD

**Issue by luispuig** [mylesmmurphy/prettify-ts#40]
Congrats for the work!

I am trying to merge and copy/paste a very long definition, but I see "... more" on the hover panel.

<img width="774" alt="image" src="https://github.com/user-attachments/assets/615cf392-5b0c-4d33-9e59-d784cc267205">

I also tried with the suggested extensions for the view panel it navigates the type but I didn't find the option to copy the nested result.

Thanks

**Comment by mylesmmurphy** [comment]
Hi @luispuig!
Thanks for mentioning. Have you tried changing the settings of the extension to allow more properties and characters to be shown? The extension truncates extremely long types by default to save on performance and readability, but this can be changed in the Prettify settings if needed, please let me know if that helps!

P.s. Sorry for the delay, we were in the path of Hurricane Milton ⛈️

**Comment by luispuig** [comment]
No problem. I think I did but I'll give them another opportunity, it could be my mistake. thanks!!!
