### ISSUE TITLE
Omitting type doesn't work correctly 

### ISSUE THREAD

**Issue by Niewdanka** [mylesmmurphy/prettify-ts#49]
Hi! Omitting types doesn't work correctly when hovering over the main type. However, it works correctly when hovering over a nested property.

Example types:
<img width="354" alt="Zrzut ekranu 2024-11-10 o 17 52 16" src="https://github.com/user-attachments/assets/072e47b3-c228-4c59-adeb-6eab750a53b0">

Here is type when i hover Main type:
<img width="354" alt="Zrzut ekranu 2024-11-10 o 17 52 23" src="https://github.com/user-attachments/assets/653a6bc4-eb2e-44c4-a1d9-783b487685b6">

Here when i hover nested prop in Main type:
<img width="354" alt="Zrzut ekranu 2024-11-10 o 17 52 27" src="https://github.com/user-attachments/assets/62112b91-70ab-4ccc-a82a-de3b64cfb1f5">

**Comment by mylesmmurphy** [comment]
Hey @Niewdanka! Thanks for mentioning this. What you are seeing is actually the default behavior of this extension, which aims to provide a better preview, but not necessarily _complete_ type information. However, this is all customizable to your liking. You should be able to go into the extension's settings and modify the "depth" property to a higher value (default is 1), which will then show deeply nested complex types at the root level. Please let me know if you have any questions or suggestions! 😄

**Comment by Niewdanka** [comment]
Thank you for the clarification! It works as expected :D
