### ISSUE TITLE
Object nesting missing one tab

### ISSUE THREAD

**Issue by Uziniii** [mylesmmurphy/prettify-ts#7]
That happen when I do [key: any]

![image](https://github.com/mylesmmurphy/prettify-ts/assets/43294422/38a51b73-bb84-4686-a6b4-9e3dc52b60ce)

**Comment by mylesmmurphy** [comment]
Hi @Uziniii, thanks for pointing this out! I will look into it and hopefully will have a resolution within a couple of days.

**Comment by mylesmmurphy** [comment]
Potential fix here: https://github.com/mylesmmurphy/prettify-ts/pull/8

**Comment by mylesmmurphy** [comment]
Just published v0.0.16 which includes the fix for this issue. It's not an ideal fix, but it works for now and is much faster than other formatting options. 😄
